/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.ClienteDao;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import utils.Mensagens;

public class TelaCliente extends javax.swing.JFrame {

    Cliente cliente = new Cliente();
    ClienteDao dao = null;

    /**
     * Creates new form Cliente
     */
    public TelaCliente() {
        initComponents();
        preecheTabela();
        lbl_id.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_cadastrar = new javax.swing.JButton();
        txt_nome_cliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_cpf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_telefone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_alterar1 = new javax.swing.JButton();
        btn_excluir1 = new javax.swing.JButton();
        lbl_id = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_cidade = new javax.swing.JTextField();
        txt_rua = new javax.swing.JTextField();
        txt_n = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_cliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        txt_nome_cliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("CPF");

        txt_cpf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cpfActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Rua");

        txt_telefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Telefone");

        btn_alterar1.setText("Alterar");
        btn_alterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterar1ActionPerformed(evt);
            }
        });

        btn_excluir1.setText("Excluir");
        btn_excluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir1ActionPerformed(evt);
            }
        });

        lbl_id.setText("1");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Nome");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Cidade");

        txt_cidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txt_rua.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txt_n.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Nº");

        table_cliente.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        table_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "Rua", "N", "Cidade", "Telefone"
            }
        ));
        table_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_clienteMouseClicked(evt);
            }
        });
        table_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table_clienteKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table_cliente);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_n, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(291, 291, 291))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(txt_nome_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(txt_rua, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel12))))
                                    .addComponent(jLabel8)
                                    .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_alterar1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_excluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_nome_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_rua, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_n, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btn_excluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(lbl_id))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(btn_alterar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(989, 565));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        cadastrar();
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void txt_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cpfActionPerformed

    private void btn_alterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterar1ActionPerformed
        atualizar();
    }//GEN-LAST:event_btn_alterar1ActionPerformed

    private void btn_excluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir1ActionPerformed
        apagar();
    }//GEN-LAST:event_btn_excluir1ActionPerformed

    private void table_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_clienteMouseClicked
        if (table_cliente.getSelectedRow() != -1) {
            lbl_id.setText(table_cliente.getValueAt(table_cliente.getSelectedRow(), 0).toString());
            txt_nome_cliente.setText(table_cliente.getValueAt(table_cliente.getSelectedRow(), 1).toString());
            txt_cpf.setText(table_cliente.getValueAt(table_cliente.getSelectedRow(), 2).toString());
            txt_rua.setText(table_cliente.getValueAt(table_cliente.getSelectedRow(), 3).toString());
            txt_n.setText(table_cliente.getValueAt(table_cliente.getSelectedRow(), 4).toString());
            txt_cidade.setText(table_cliente.getValueAt(table_cliente.getSelectedRow(), 5).toString());
            txt_telefone.setText(table_cliente.getValueAt(table_cliente.getSelectedRow(), 6).toString());
            btn_cadastrar.setEnabled(false);
        }
    }//GEN-LAST:event_table_clienteMouseClicked

    private void table_clienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_clienteKeyReleased

        if (table_cliente.getSelectedRow() != -1) {
            lbl_id.setText(table_cliente.getValueAt(table_cliente.getSelectedRow(), 0).toString());
            txt_nome_cliente.setText(table_cliente.getValueAt(table_cliente.getSelectedRow(), 1).toString());
            txt_cpf.setText(table_cliente.getValueAt(table_cliente.getSelectedRow(), 2).toString());
            txt_rua.setText(table_cliente.getValueAt(table_cliente.getSelectedRow(), 3).toString());
            txt_n.setText(table_cliente.getValueAt(table_cliente.getSelectedRow(), 4).toString());
            txt_cidade.setText(table_cliente.getValueAt(table_cliente.getSelectedRow(), 5).toString());
            txt_telefone.setText(table_cliente.getValueAt(table_cliente.getSelectedRow(), 6).toString());
            btn_cadastrar.setEnabled(false);
        }
    }//GEN-LAST:event_table_clienteKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar1;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_excluir1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JTable table_cliente;
    private javax.swing.JTextField txt_cidade;
    private javax.swing.JTextField txt_cpf;
    private javax.swing.JTextField txt_n;
    private javax.swing.JTextField txt_nome_cliente;
    private javax.swing.JTextField txt_rua;
    private javax.swing.JTextField txt_telefone;
    // End of variables declaration//GEN-END:variables

    private void cadastrar() {
        try {
            cliente.setNome(txt_nome_cliente.getText());
            cliente.setCpf(txt_cpf.getText());
            cliente.getEndereco().setRua(txt_rua.getText());
            cliente.getEndereco().setNumero(txt_n.getText());
            cliente.getEndereco().setCidade(txt_cidade.getText());
            cliente.setTelefone(txt_telefone.getText());

            dao.inserir(cliente);
            Mensagens.mensagemConfirmacao("Cliente cadastrado com sucesso!");
        } catch (Exception e) {
            Mensagens.mensagemErro(e.getMessage());
        }
        preecheTabela();
        limpaCampos();

    }

    private void atualizar() {
        try {
            btn_cadastrar.setEnabled(true);
            cliente.setNome(txt_nome_cliente.getText());
            cliente.setCpf(txt_cpf.getText());
            cliente.getEndereco().setRua(txt_rua.getText());
            cliente.getEndereco().setNumero(txt_n.getText());
            cliente.getEndereco().setCidade(txt_cidade.getText());
            cliente.setTelefone(txt_telefone.getText());
            cliente.setId(Integer.parseInt(lbl_id.getText()));

            dao.editar(cliente);
            Mensagens.mensagemConfirmacao("Cliente atualizado com sucesso!");
        } catch (Exception e) {
            Mensagens.mensagemErro(e.getMessage());
        }
        preecheTabela();
        limpaCampos();

    }

    private void apagar() {
        try {
            btn_cadastrar.setEnabled(true);
            cliente.setNome(txt_nome_cliente.getText());
            cliente.setCpf(txt_cpf.getText());
            cliente.getEndereco().setRua(txt_rua.getText());
            cliente.getEndereco().setNumero(txt_n.getText());
            cliente.getEndereco().setCidade(txt_cidade.getText());
            cliente.setTelefone(txt_telefone.getText());
            cliente.setId(Integer.parseInt(lbl_id.getText()));

            dao.excluir(cliente);
            Mensagens.mensagemConfirmacao("Cliente deletado com sucesso!");
        } catch (Exception e) {
            Mensagens.mensagemErro(e.getMessage());
        }
        preecheTabela();
        limpaCampos();

    }

    private void preecheTabela() {
        try {
            DefaultTableModel modelo = (DefaultTableModel) table_cliente.getModel();
            modelo.setNumRows(0);
            dao = new ClienteDao();
            for (Cliente clientes : dao.listar()) {
                modelo.addRow(new Object[]{clientes.getId(),
                    clientes.getNome(),
                    clientes.getCpf(),
                    clientes.getEndereco().getRua(),
                    clientes.getEndereco().getNumero(),
                    clientes.getEndereco().getCidade(),
                    clientes.getTelefone()});
            }
        } catch (Exception e) {
            Mensagens.mensagemErro(e.getMessage());
        }
    }

    private void limpaCampos() {
        txt_nome_cliente.setText("");
        txt_cpf.setText("");
        txt_rua.setText("");
        txt_n.setText("");
        txt_cidade.setText("");
        txt_telefone.setText("");
        lbl_id.setText("");
    }

}
