/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.FilmeDao;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Filme;
import utils.Mensagens;

/**
 *
 * @author francisco
 */
public class TelaLoc extends javax.swing.JFrame {

    FilmeDao daoF = null;
    Filme filme = null;

    /**
     * Creates new form TelaLoc
     */
    public TelaLoc() {
        initComponents();
        preecheTabela();
        DefaultTableModel modelo = (DefaultTableModel) table_filme.getModel();
        table_filme.setRowSorter(new TableRowSorter(modelo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        txt_cliente = new javax.swing.JTextField();
        txt_status = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_filme = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_DataLocacao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_DataDevolucao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_filme = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Nome do Cliente");

        txt_cliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_clienteActionPerformed(evt);
            }
        });

        txt_status.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Status:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Nome do Filme");

        txt_filme.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Data de Locação");

        txt_DataLocacao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Data de Devolução");

        txt_DataDevolucao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        table_filme.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        table_filme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Gênero", "Informação", "Disponivel", "Qtd", "Valor"
            }
        ));
        table_filme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_filmeMouseClicked(evt);
            }
        });
        table_filme.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table_filmeKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table_filme);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txt_DataLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_DataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(txt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel6)
                        .addComponent(txt_filme, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(319, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_DataLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(11, 11, 11)
                .addComponent(txt_DataDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(7, 7, 7)
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(txt_filme, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(286, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(887, 458));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_clienteActionPerformed

    private void table_filmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_filmeMouseClicked
                if (table_filme.getSelectedRow() != -1) {
                    filme = new Filme();
                    filme.setId((Integer) table_filme.getValueAt(table_filme.getSelectedRow(), 0));
                    filme.setTitulo((String) table_filme.getValueAt(table_filme.getSelectedRow(), 1));
                    filme.setGenero((String) table_filme.getValueAt(table_filme.getSelectedRow(), 2));
                    filme.setInformacao((String) table_filme.getValueAt(table_filme.getSelectedRow(), 3));
                    filme.setDisponivel((String) table_filme.getValueAt(table_filme.getSelectedRow(), 4));
                    filme.setQuantidade((Integer) table_filme.getValueAt(table_filme.getSelectedRow(), 5));
                    filme.setValor((Double) table_filme.getValueAt(table_filme.getSelectedRow(), 6));
                    System.out.println(filme);
                    //  btn_cadastrar.setEnabled(false);
                }
    }//GEN-LAST:event_table_filmeMouseClicked

    private void table_filmeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_filmeKeyReleased

        //        if (table_filme.getSelectedRow() != -1) {
        ////            lbl_id_filme.setText(table_filme.getValueAt(table_filme.getSelectedRow(), 0).toString());
        ////            lbl_titulo_filme.setText(table_filme.getValueAt(table_filme.getSelectedRow(), 1).toString());
        ////            lbl_genero_filme.setText(table_filme.getValueAt(table_filme.getSelectedRow(), 2).toString());
        ////            lbl_informacao_filme.setText(table_filme.getValueAt(table_filme.getSelectedRow(), 3).toString());
        ////            lbl_disponivel_filme.setText(table_filme.getValueAt(table_filme.getSelectedRow(), 4).toString());
        ////            lbl_quantidade_filme.setText(table_filme.getValueAt(table_filme.getSelectedRow(), 5).toString());
        ////            lbl_valor_filme.setText(table_filme.getValueAt(table_filme.getSelectedRow(), 6).toString());
        //        }
    }//GEN-LAST:event_table_filmeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_filme;
    private javax.swing.JTextField txt_DataDevolucao;
    private javax.swing.JTextField txt_DataLocacao;
    private javax.swing.JTextField txt_cliente;
    private javax.swing.JTextField txt_filme;
    private javax.swing.JTextField txt_status;
    // End of variables declaration//GEN-END:variables

    private void preecheTabela() {
        try {
            DefaultTableModel modelo = (DefaultTableModel) table_filme.getModel();
            modelo.setNumRows(0);
            daoF = new FilmeDao();
            for (Filme filmes : daoF.listar()) {
                modelo.addRow(new Object[]{filmes.getId(),
                    filmes.getTitulo(),
                    filmes.getGenero(),
                    filmes.getInformacao(),
                    filmes.getDisponivel(),
                    filmes.getQuantidade(),
                    filmes.getValor()});
            }
        } catch (Exception e) {
            Mensagens.mensagemErro(e.getMessage());
        }
    }

}
