/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.FilmeDao;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Filme;
import utils.Mensagens;

/**
 *
 * @author Francisco
 */
public class TelaFilme extends javax.swing.JFrame {

    private FilmeDao dao = null;
    private Filme filme = new Filme();

    public TelaFilme() {
        initComponents();
        preecheTabela();
        DefaultTableModel modelo = (DefaultTableModel) table_filme.getModel();
        table_filme.setRowSorter(new TableRowSorter(modelo));
        txt_id.setVisible(false);
        lbl_disponivel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_quantidade = new javax.swing.JTextField();
        //try{
            //    javax.swing.text.MaskFormatter qntd = new javax.swing.text.MaskFormatter("##########");
            //    txt_quantidade = new javax.swing.JFormattedTextField(qntd);
            //   }catch(Exception e){
            //
            //}
        btn_cadastrar = new javax.swing.JButton();
        txt_titulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_genero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_informacao = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_alterar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        txt_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_valor = new javax.swing.JTextField();
        lbl_disponivel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_filme = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        txt_quantidade.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_quantidade.setText("0");
        txt_quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_quantidadeActionPerformed(evt);
            }
        });
        txt_quantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_quantidadeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_quantidadeKeyReleased(evt);
            }
        });

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        txt_titulo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Gênero");

        txt_genero.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_generoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Informação");

        txt_informacao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Qtd:");

        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Título");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Valor");

        txt_valor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lbl_disponivel.setText("Filme disponivel");

        table_filme.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        table_filme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Gênero", "Informação", "Disponivel", "Qtd", "Valor"
            }
        ));
        table_filme.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_filmeMouseClicked(evt);
            }
        });
        table_filme.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table_filmeKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table_filme);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(txt_informacao, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(txt_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addGap(167, 167, 167)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btn_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lbl_disponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(346, 346, 346)
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_informacao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_disponivel)))
                            .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1050, 621));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed

        apagar();
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed

        atualizar();
    }//GEN-LAST:event_btn_alterarActionPerformed

    private void txt_generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_generoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_generoActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        cadastrar();
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void txt_quantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_quantidadeKeyReleased
        //        new Validar().ValidaNumero(txt_quantidade);
    }//GEN-LAST:event_txt_quantidadeKeyReleased

    private void txt_quantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_quantidadeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_quantidadeKeyPressed

    private void txt_quantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_quantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_quantidadeActionPerformed

    private void table_filmeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_filmeMouseClicked
        if (table_filme.getSelectedRow() != -1) {
            txt_id.setText(table_filme.getValueAt(table_filme.getSelectedRow(), 0).toString());
            txt_titulo.setText(table_filme.getValueAt(table_filme.getSelectedRow(), 1).toString());
            txt_genero.setText(table_filme.getValueAt(table_filme.getSelectedRow(), 2).toString());
            txt_informacao.setText(table_filme.getValueAt(table_filme.getSelectedRow(), 3).toString());
            lbl_disponivel.setText(table_filme.getValueAt(table_filme.getSelectedRow(), 4).toString());
            txt_quantidade.setText(table_filme.getValueAt(table_filme.getSelectedRow(), 5).toString());
            txt_valor.setText(table_filme.getValueAt(table_filme.getSelectedRow(), 6).toString());
            btn_cadastrar.setEnabled(false);
        }
    }//GEN-LAST:event_table_filmeMouseClicked

    private void table_filmeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_filmeKeyReleased

        if (table_filme.getSelectedRow() != -1) {
            txt_id.setText(table_filme.getValueAt(table_filme.getSelectedRow(), 0).toString());
            txt_titulo.setText(table_filme.getValueAt(table_filme.getSelectedRow(), 1).toString());
            txt_genero.setText(table_filme.getValueAt(table_filme.getSelectedRow(), 2).toString());
            txt_informacao.setText(table_filme.getValueAt(table_filme.getSelectedRow(), 3).toString());
            lbl_disponivel.setText(table_filme.getValueAt(table_filme.getSelectedRow(), 4).toString());
            txt_quantidade.setText(table_filme.getValueAt(table_filme.getSelectedRow(), 5).toString());
            txt_valor.setText(table_filme.getValueAt(table_filme.getSelectedRow(), 6).toString());
        }
    }//GEN-LAST:event_table_filmeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFilme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_disponivel;
    private javax.swing.JTable table_filme;
    private javax.swing.JTextField txt_genero;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_informacao;
    private javax.swing.JTextField txt_quantidade;
    private javax.swing.JTextField txt_titulo;
    private javax.swing.JTextField txt_valor;
    // End of variables declaration//GEN-END:variables

    private void cadastrar() {
        try {
            filme.setTitulo(txt_titulo.getText());
            filme.setGenero(txt_genero.getText());
            filme.setInformacao(txt_informacao.getText());
            filme.setQuantidade(Integer.parseInt(txt_quantidade.getText()));
            filme.setValor(Double.parseDouble(txt_valor.getText()));
            filme.setDisponivel(lbl_disponivel.getText());
            dao.inserir(filme);
            Mensagens.mensagemConfirmacao("Filme cadastrado com sucesso!");
        } catch (Exception e) {
            Mensagens.mensagemErro(e.getMessage());
        }
        preecheTabela();
        limpaCampos();

    }

    private void atualizar() {
        try {
            btn_cadastrar.setEnabled(true);
            filme.setTitulo(txt_titulo.getText());
            filme.setGenero(txt_genero.getText());
            filme.setInformacao(txt_informacao.getText());
            filme.setQuantidade(Integer.parseInt(txt_quantidade.getText()));
            filme.setValor(Double.parseDouble(txt_valor.getText()));
            filme.filmeDisponivel();
            filme.setId(Integer.parseInt(txt_id.getText()));

            dao.editar(filme);
            Mensagens.mensagemConfirmacao("Filme atualizado com sucesso!");
        } catch (Exception e) {
            Mensagens.mensagemErro(e.getMessage());
        }
        preecheTabela();
        limpaCampos();

    }

    private void apagar() {
        try {
            btn_cadastrar.setEnabled(true);
            filme.setTitulo(txt_titulo.getText());
            filme.setGenero(txt_genero.getText());
            filme.setInformacao(txt_informacao.getText());
            filme.setQuantidade(Integer.parseInt(txt_quantidade.getText()));
            filme.setValor(Double.parseDouble(txt_valor.getText()));
            filme.setDisponivel(lbl_disponivel.getText());
            filme.setId(Integer.parseInt(txt_id.getText()));

            dao.excluir(filme);
            Mensagens.mensagemConfirmacao("Filme deletado com sucesso!");
        } catch (Exception e) {
            Mensagens.mensagemErro(e.getMessage());
        }
        preecheTabela();
        limpaCampos();

    }

    private void preecheTabela() {
        try {
            DefaultTableModel modelo = (DefaultTableModel) table_filme.getModel();
            modelo.setNumRows(0);
            dao = new FilmeDao();
            for (Filme filmes : dao.listar()) {
                modelo.addRow(new Object[]{filmes.getId(),
                    filmes.getTitulo(),
                    filmes.getGenero(),
                    filmes.getInformacao(),
                    filmes.getDisponivel(),
                    filmes.getQuantidade(),
                    filmes.getValor()});
            }
        } catch (Exception e) {
            Mensagens.mensagemErro(e.getMessage());
        }
    }

    private void limpaCampos() {
        txt_titulo.setText("");
        txt_genero.setText("");
        txt_informacao.setText("");
        txt_quantidade.setText("");
        txt_valor.setText("");
        txt_id.setText("");
    }

}
